/****************************************************************************
*   Generated by ACUITY 6.21.1
*   Match ovxlib 1.1.53
*
*   Neural Network appliction post-process header file
****************************************************************************/
#ifndef _VNN_POST_PROCESS_ANTISPOOF_H_
#define _VNN_POST_PROCESS_ANTISPOOF_H_

float vnn_PostProcessAntiSpoof(vsi_nn_graph_t *graph);

// const vsi_nn_postprocess_map_element_t * vnn_GetPostProcessMap();

// uint32_t vnn_GetPostProcessMapCount();

#endif
