/****************************************************************************
*   Generated by ACUITY 6.21.1
*   Match ovxlib 1.1.53
*
*   Neural Network appliction post-process header file
****************************************************************************/
#ifndef _VNN_POST_PROCESS_SFACE_H_
#define _VNN_POST_PROCESS_SFACE_H_

#include <vector>

vsi_status vnn_PostProcessSface(vsi_nn_graph_t *graph);
std::vector<float> vnn_PostProcessSfaceExtractFeature(vsi_nn_graph_t *graph);

const vsi_nn_postprocess_map_element_t * vnn_GetPostProcessMap();

uint32_t vnn_GetPostProcessMapCount();

#endif
